version: '3.1'

networks:
  cookie:

services:

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 8080:8080
    environment:
      BACKEND_DNS: backend
    networks:
      - cookie

  backend:
    build: ./backend
    restart: always
    networks:
      - cookie
