apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: andreasga/sfc-frontend:latest
        name: sfc-frontend
        env:
        - name: BACKEND_DNS
          value: "backend"
        - name: BACKEND_PORT
          value: "9000"
        ports:
        - containerPort: 8080
        resources: {}
status: {}
