resources:
- frontend-deploy.yml
- backend-deploy.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: andreasga/sfc-backend
  newName: andreasga/sfc-backend
  newTag: latest
- name: andreasga/sfc-frontend
  newName: andreasga/sfc-frontend
  newTag: latest
