name: Build and Push to DockerHub
on:
  push:
  pull_request:
    types:
    - opened
jobs:
  docker_build_and_push:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Build docker images and push to dockerhub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build and push backend
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        image_name: andreasga/sfc-backend
        tags: "latest,{{ steps.vars.outputs.sha_short }}"
    - name: Build and push frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        image_name: andreasga/sfc-frontend
        tags: "latest,{{ steps.vars.outputs.sha_short }}"
