name: Test
on: push
jobs:
  frontend_test:
    name: Test frontend
    runs-on: ubuntu-latest
    container: golang:1.17.2-bullseye
    steps:
    - uses: actions/checkout@v2
    - name: Go test frontend
      run: cd frontend && go test
  integration_test:
    name: Test full stack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run docker-compose
      run: docker-compose up -d
    - name: Curl test
      run: ./curl_test.sh
        #integration_test_cleanup:
        #  name: Clean up
        #  needs: integration_test
        #  runs-on: ubuntu-latest
        #  steps:
        #  - name: clean up
        #    run: docker-compose down
